# Generated by Django 5.2.1 on 2025-07-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='p_type',
            new_name='post_type',
        ),
    ]
