# Generated by Django 5.2.1 on 2025-08-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_p_type_post_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_like',
        ),
    ]
