# Generated by Django 5.2.1 on 2025-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_comment_comment_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.IntegerField(default=0),
        ),
    ]
